### PR TITLE
Create autoload entries for composer

### PR DESCRIPTION
**Pull request by judgej**
When used in a composer-based application (e.g. Laravel) these changes will ensure the classes are available to the application. There are two methods used here - you may want them both, or just one or the other. Here is how they work:

* The `autoload/files` entry is the equivalent to an `include`. It will load the main bootstrap file in this package on every page load. Loading that bootstrap file will then load all the classes in the package, again, on every page load.
* The `autoload\classmap` takes a different approach. This will scan the package for php scripts, then extract all the classes it finds, and sets up a register of where all those classes are. When any of those classes are used, the composer autoloader will kick in and load the appropriate file. The classes will only be loaded when they are actually used. It will load the classes in the order they are used, and will not attempt to load the bootstrap file first, since it has no need for the bootstrap file.

So, the first method has an overhead on pages the package is not needed, but it will execute everything that the package is expecting to be loaded and in the right order. The second method is more efficient, only loading classes as they are needed and used (down to individual classes - if you don't access the projects resource, then that class is not loaded), but will skip the bootstrap script that may have some logic in that you are expecting to be run.

Personally, I would go for the classmap approach, so long as you are happy that not running the bootstrap file will be okay, perhaps removing some logic from the bootstrap `lib/woocommerce-api.php` script. Both methods are in here, but I can remove either, or we can leave both in and decide later.

### CODE REVIEW

**Comment by judgej** [comment]
So with these changes, you just `require` this package in the project `composer.json`, then just use it anywhere in the project - go straight into `$client = new \WC_API_Client(...)` without any other required steps, and it *just works* (which is how we like it).

**Comment by judgej** [comment]
Of course, the best option would be to go PHP 5.4+ with namespaces and PSR-4 autoloading. But this will work as an interim measure.

**Comment by judgej** [comment]
Looking at the bootstrap, the only code is has in there that is not a simple `include` is this:
~~~php
// required functions
if ( ! extension_loaded( 'curl' ) ) {
	throw new Exception( 'WooCommerce REST API client requires the cURL PHP extension.' );
}
if ( ! extension_loaded( 'json' ) ) {
	throw new Exception( 'WooCommerce REST API client needs the JSON extension.' );
}
~~~

IMO that could be moved to the constructor of the WC_API_Client class - there is no need to check these things until it is needed. If that is done, then the "file" entry from `composer.phar` in this PR can be removed, so the classes are not loaded on each page load. The classes will be autoloaded as and when needed instead, using the classmap index that composer generates. Nothing will really change for users not using composer, but performance will be improved for those that are.

Does this approach sound okay to you? I can apply those changes to this PR if you like, or leave if for you to think about and maybe apply later (or not).

**Comment by judgej** [comment]
Just noticed in `WC_API_Client::init_resources()` all the resources are instantiated, whether they are needed or not. That will result in all scripts in this package being loaded as soon as `WC_API_Client` is instantiated for the first time. Is that really necessary? Can they not be instantiated only when needed? `Pimple` may give some ideas on how this can be done - effectively storing an instantiator function in each element of the DI container, so when each is first accessed, the object is instantiated, but not before then. That's just one approach, anyway.

**Comment by maxrice** [comment]
@judgej thanks so much for putting this together, the autoload stuff looks good to me. I'm fine with moving those `curl` and `json` extension checks to the constructor as well. Feel free to add that change to this PR and I'll merge.

`WC_API_Client::init_resources()` could certainly be refactored to be a bit more lightweight though IMO I don't think there's enough code there for a refactoring to really make a difference. If you want to work up a PR to change that and instantiate as needed, I'd be happy to review and merge :smile_cat:

**Comment by judgej** [comment]
Should be there now. curl/xml function check moved to `WC_API_Client` constructor. "file" autoload composer entry pointing to `lib/woocommerce-api.php` has been removed, leaving just the classmap entry.

I've removed this package from my dev site and reinstalled from the PR instance, and all works nicely.

Refactoring `WC_API_Client::init_resources()` is probably a different thing, so I won't try and squeeze that into this PR.

**Comment by maxrice** [comment]
:beers: looks good, thanks :)

**Pull request merged**
