### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by maxrice**
[WIP, do not merge yet.]

This is the first draft of the v2 client lib -- it only supports the v2 REST API and is designed to be more flexible and tolerant of errors or weirdness in site configurations. I've decided not to make it backwards compatible with the current version since it's designed very differently.

Some sample code:

```php
require_once( 'lib/woocommerce-api.php' );

$options = array(
	'verbose_mode'    => true,
	'return_as_array' => false,
	'validate_url'    => true,
);

try {

	$client = new WC_API_Client( 'http://example.com', 'ck_1234', 'cs_1234', $options );

	// get all orders
	print_r( $client->orders->get() );

	// update an order
	$order = $client->orders->get( 21495 );

	$order->order->billing_address->first_name = 'Maximus';

	print_r( $order = $client->orders->update( 21495, $order ) );

	// example of convenience method
	$client->orders->update_status( 21495, 'completed' );

} catch ( WC_API_Client_Exception $e ) {

	echo $e->getMessage() . PHP_EOL;
	echo $e->getCode() . PHP_EOL;
	echo $e->get_raw_error() . PHP_EOL;
}
```

## TODO

- [X] Add resources
  - [X] Index, completed in SHA: cca8590a31eb9bd681e1418f74fdcfe9f99cdbc6
  - [X] Coupons, completed in SHA: 7c54b432ddbfcecbb8990045a8255ff93f175258
  - [X] Customers, completed in SHA: e85c31036fbf4ab7c6f05a2dc4de75acd61caf6d
  - [X] Order Notes, completed in SHA: e7c7ed10f6433636a3f85ea1b13441f13b89fc87
  - [X] Order Refunds, completed in SHA: d394b23ed445f28f290bca5bdad9baaab320f4c6
  - [X] Products, completed in SHA: 1e14ed093985698ee4056fca39b9775225744a56
  - [X] Reports, completed in SHA: b3abb054198880c8a200bbd065e1bcf26b1dc5d0
  - [X] Webhooks, completed in SHA: fdd1e9959c8948c2cf176600d2f833dc9654a468
- [X] support for custom endpoints, completed in SHA: ef83c86d0197e601fbab9cd48fdd8a64940d2e66
- [X] support for setting additional HTTP options, like timeout, completed in SHA: a93d4ce086a2f986d4affdd131265e8b98db96d5

@kloon @claudiosmweb would love your feedback :smile_cat:

### CODE REVIEW

**Comment by peardox** [comment]
@maxrice 

Have you done webhooks yet?

There is an (ignorable) issue passing an array for the hooks that causes an authentication PHP error (still works)

	public function get_webhooks() {
		return $this->_make_api_call( 'webhooks' );
	}

	public function set_webhook( $params = array() ) {
		return $this->_make_api_call( 'webhooks', array('webhook' => $params), 'POST' );
	}

	public function delete_webhook( $id ) {
		return $this->_make_api_call( 'webhooks/'.(int) $id, array(), 'DELETE' );
       }

WORKs with v2 but the dox say pass JSON

The thing that causes the issue is normalize_parameters() not handlig arrays properly (same goes for the Woo end of things)

Not tested this on 2.3 yet tho

**Comment by maxrice** [comment]
@peardox haven't done them yet, but there shouldn't be any issue with creating webhooks -- I tested them extensively when I added in 2.2 and didn't see any issues. The request body isn't signed when using OAuth 1.0a so the `normalize_parameters()` method shouldn't be invoked on it. Do you have the exact error message that you've seen?

**Comment by peardox** [comment]
This is core...

rawurldecode() expects parameter 1 to be string, array given in <somewhere>/wp-content/plugins/woocommerce/includes/api/class-wc-api-authentication.php on line 280

The same function is used in the v1 API client and my hacked v2

Specifically normalize_parameters

If you check the code it doesn't cater for arrays when it scans the parameters

**Comment by kloon** [comment]
@maxrice Only had a chance to glance over this now, looks good. Love the fact that everything is split up into modules, just makes extending it so much easier.

Looks like you only implemented orders for now? Let me know if you need help with other endpoints.

**Comment by maxrice** [comment]
@kloon thanks :)

I'll take a shot at implementing the other endpoints now, shouldn't be too hard to get them all added since they follow the same sort of pattern.

**Comment by documarezc** [comment]
What about an update_product function to update a product?

Thanks,

David.

**Comment by maxrice** [comment]
@documarezc coming soon :) just need to add that product endpoint.

**Comment by documarezc** [comment]
@maxrice I was working on that this weekend. I download a copy and write the code for my own use. I would like to collaborate if you want, thanks.

**Comment by maxrice** [comment]
@documarezc sure, if you pull this branch down, you should be able to open a PR with changes to it (I think) -- otherwise feel free to put what you wrote in a gist and I'll integrate it in here. Were you using this new version?

**Comment by documarezc** [comment]
@maxrice Ok great, I will do. I am using it in an Integration between FBA and a Woocommerce Store

**Comment by bryceadams** [comment]
great work on this @maxrice

**Comment by claudiosmweb** [comment]
@maxrice I had the chance to see the code now and really liked it.

**Comment by mdorchain** [comment]
The new v2 looks really promising. I really like the structure and the exceptions management.
Not sure why on the first test I get Invalid Signature error on $client->orders->get().
I don't have any issue on the v1 even if I use the v2 endpoints.. Any particular reason or things I overlooked?

**Pull request merged**
